

# Setup
title:               DBpedia Development
tagline:             'The DBpedia development platform'
url:                 'http://dev.dbpedia.org'
description:          'Short and smart description about this site. Visit <a href="https://wiki.dbpedia.org/blog/dbpedia-databus-%E2%80%93-transforming-linked-data-networked-data-economy" target="_blank">The DBpedia Databus</a> for more information.'
baseurl:             'http://dev.dbpedia.org'

permalink:           pretty

# About/contact
author:
  name:              Marvin Hofer
# url:
  email:             hofer@informatik.uni-leipzig.de

# Custom vars
version:             1.0.0
