

# Setup
title:               DBpedia Development Wiki
tagline:             'devilopment bible'
url:                 'http://dev.dbpedia.org'
description:          'A central collection of everything DBpedia.<img src="https://wiki.dbpedia.org/sites/default/files/DBpediaLogoFull.png"></img>'
baseurl:             'http://dev.dbpedia.org'

permalink:           pretty

# About/contact
author:
  name:              Marvin Hofer
# url:
  email:             hofer@informatik.uni-leipzig.de

# Custom vars
version:             1.0.0
